# Generated by Django 3.0.6 on 2020-05-23 09:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Art'), ('2', 'Buisness'), ('Cooking', 'Cooking'), ('4', 'Design'), ('5', 'Education'), ('6', 'Engineering'), ('7', 'Entertainment'), ('8', 'Food'), ('9', 'Goverment')], max_length=23, verbose_name='Category...'),
        ),
    ]
