# Generated by Django 3.0.6 on 2020-05-23 09:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200523_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10', 'Healthcare'), ('11', 'Languages'), ('12', 'Law'), ('13', 'Mathematics'), ('Politics', 'Politics'), ('15', 'Science'), ('16', 'Sports'), ('17', 'Technology'), ('18', 'Traveling')], max_length=32, verbose_name='Category...'),
        ),
    ]
