# Generated by Django 3.0.6 on 2020-05-30 07:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200523_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Art'), (2, 'Buisness'), (3, 'Cooking'), (4, 'Design'), (5, 'Education'), (6, 'Engineering'), (7, 'Entertainment'), (8, 'Food'), (9, 'Goverment'), (10, 'Healthcare'), (11, 'Languages'), (12, 'Law'), (13, 'Mathematics'), (14, 'Politics'), (15, 'Science'), (16, 'Sports'), (17, 'Technology'), (18, 'Traveling')], max_length=44, verbose_name='Select tags for your post...'),
        ),
    ]
