# Generated by Django 3.0.7 on 2020-06-10 15:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200609_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
