# Generated by Django 3.1.2 on 2021-02-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210217_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
