# Generated by Django 3.0.6 on 2020-05-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200523_1110'),
        ('users', '0002_auto_20200525_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
