# Generated by Django 3.0.7 on 2020-06-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200525_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Tell us more about yourself...', max_length=150, verbose_name='Tell us more about yourself...'),
        ),
    ]
