# Generated by Django 3.1.2 on 2021-02-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210219_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='savepost',
            old_name='user',
            new_name='author',
        ),
    ]
